program PromaharinClient;

uses
  MidasLib,
  Vcl.Forms,
  Main.Form.Menu in 'Main.Form.Menu.pas' {frmMain},
  Catalog.Form.Product in 'Catalog.Form.Product.pas' {frmProduct},
  Catalog.Form.Provider in 'Catalog.Form.Provider.pas' {frmProvider},
  Module.Form.Inventory in 'Module.Form.Inventory.pas' {frmInventory},
  Catalog.Data.Product in 'Catalog.Data.Product.pas' {dmProduct: TDataModule},
  Catalog.Data.Provider in 'Catalog.Data.Provider.pas' {dmProvider: TDataModule},
  Module.Data.Inventory in 'Module.Data.Inventory.pas' {dmInventory: TDataModule},
  Main.Data.Global in 'Main.Data.Global.pas' {dmGlobal: TDataModule},
  Core.Form.Base in 'Core.Form.Base.pas' {frmBase},
  Common.Form.List in 'Common.Form.List.pas' {frmList},
  Common.Data.Master in 'Common.Data.Master.pas' {dmMaster: TDataModule},
  Core.Form.Master in 'Core.Form.Master.pas' {frmMaster},
  Core.Data.Base in 'Core.Data.Base.pas' {dmBase: TDataModule},
  Common.Form.Module in 'Common.Form.Module.pas' {frmModule},
  Common.Data.Search in 'Common.Data.Search.pas' {dmSearch: TDataModule},
  Common.Form.Search in 'Common.Form.Search.pas' {frmSearch},
  Common.Control.CodeLookup in 'Common.Control.CodeLookup.pas' {ctlCodeLookup: TFrame},
  Catalog.Form.Truck in 'Catalog.Form.Truck.pas' {frmTruck},
  Catalog.Data.Truck in 'Catalog.Data.Truck.pas' {dmTruck: TDataModule},
  Catalog.Data.Destination in 'Catalog.Data.Destination.pas' {dmDestination: TDataModule},
  Catalog.Form.Destination in 'Catalog.Form.Destination.pas' {frmDestination},
  Catalog.Data.Driver in 'Catalog.Data.Driver.pas' {dmDriver: TDataModule},
  Catalog.Form.Driver in 'Catalog.Form.Driver.pas' {frmDriver},
  Catalog.Data.Supplier in 'Catalog.Data.Supplier.pas' {dmSupplier: TDataModule},
  Catalog.Form.Supplier in 'Catalog.Form.Supplier.pas' {frmSupplier},
  Module.Data.Batch in 'Module.Data.Batch.pas' {dmBatch: TDataModule},
  Module.Form.Batch in 'Module.Form.Batch.pas' {frmBatch},
  Catalog.Form.Fuel in 'Catalog.Form.Fuel.pas' {frmFuel},
  Catalog.Data.Fuel in 'Catalog.Data.Fuel.pas' {dmFuel: TDataModule},
  Catalog.Data.Provisioner in 'Catalog.Data.Provisioner.pas' {dmProvisioner: TDataModule},
  Catalog.Form.Provisioner in 'Catalog.Form.Provisioner.pas' {frmProvisioner},
  Module.Data.Refuel in 'Module.Data.Refuel.pas' {dmRefuel: TDataModule},
  Module.Form.Refuel in 'Module.Form.Refuel.pas' {frmRefuel},
  Report.Data.Stock in 'Report.Data.Stock.pas' {dmStock: TDataModule},
  Report.Form.Stock in 'Report.Form.Stock.pas' {frmStock},
  ApplicationVersionHelper in 'ApplicationVersionHelper.pas',
  VersionInfo in 'VersionInfo.pas',
  Search.Form.Provisioner in 'Search.Form.Provisioner.pas' {frmProvisionerSearch},
  Search.Form.Destination in 'Search.Form.Destination.pas' {frmDestinationSearch},
  Search.Form.Driver in 'Search.Form.Driver.pas' {frmDriverSearch},
  Search.Form.Fuel in 'Search.Form.Fuel.pas' {frmFuelSearch},
  Search.Form.Product in 'Search.Form.Product.pas' {frmProductSearch},
  Search.Form.Provider in 'Search.Form.Provider.pas' {frmProviderSearch},
  Search.Form.Supplier in 'Search.Form.Supplier.pas' {frmSupplierSearch},
  Search.Form.Truck in 'Search.Form.Truck.pas' {frmTruckSearch},
  Module.Data.Reception in 'Module.Data.Reception.pas' {dmReception: TDataModule},
  Module.Form.Reception in 'Module.Form.Reception.pas' {frmReception},
  Main.Form.Splash in 'Main.Form.Splash.pas' {frmSplash},
  Common.Data.Module in 'Common.Data.Module.pas' {dmModule: TDataModule},
  Catalog.Data.Account in 'Catalog.Data.Account.pas' {dmAccount: TDataModule},
  Catalog.Form.Account in 'Catalog.Form.Account.pas' {frmAccount},
  Catalog.Data.Category in 'Catalog.Data.Category.pas' {dmCategory: TDataModule},
  Catalog.Form.Category in 'Catalog.Form.Category.pas' {frmCategory},
  Module.Data.Outputs in 'Module.Data.Outputs.pas' {dmOutputs: TDataModule},
  Module.Form.Outputs in 'Module.Form.Outputs.pas' {frmOutputs},
  Search.Form.Category in 'Search.Form.Category.pas' {frmCategorySearch},
  Consult.Form.Account in 'Consult.Form.Account.pas' {frmAccountConsult},
  Module.Data.Inputs in 'Module.Data.Inputs.pas' {dmInputs: TDataModule},
  Module.Form.Inputs in 'Module.Form.Inputs.pas' {frmInputs},
  Catalog.Data.Client in 'Catalog.Data.Client.pas' {dmClient: TDataModule},
  Catalog.Form.Client in 'Catalog.Form.Client.pas' {frmClient},
  Search.Form.Client in 'Search.Form.Client.pas' {frmClientSearch},
  Module.Data.Quotation in 'Module.Data.Quotation.pas' {dmQuotation: TDataModule},
  Module.Form.Quotation in 'Module.Form.Quotation.pas' {frmQuotation},
  Catalog.Data.Condition in 'Catalog.Data.Condition.pas' {dmCondition: TDataModule},
  Catalog.Form.Condition in 'Catalog.Form.Condition.pas' {frmCondition},
  Catalog.Data.Seller in 'Catalog.Data.Seller.pas' {dmSeller: TDataModule},
  Catalog.Form.Seller in 'Catalog.Form.Seller.pas' {frmSeller},
  Search.Form.Seller in 'Search.Form.Seller.pas' {frmSellerSearch},
  Catalog.Data.Caterer in 'Catalog.Data.Caterer.pas' {dmCaterer: TDataModule},
  Search.Form.Caterer in 'Search.Form.Caterer.pas' {frmCatererSearch},
  Catalog.Form.Caterer in 'Catalog.Form.Caterer.pas' {frmCaterer},
  Module.Data.Order in 'Module.Data.Order.pas' {dmOrder: TDataModule},
  Module.Form.Order in 'Module.Form.Order.pas' {frmOrder};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TdmGlobal, dmGlobal);
  Application.CreateForm(TfrmMain, frmMain);
  Application.Run;
end.
